version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    links:
      - portalweb
      - portalapi

  portalweb:
    image: mophos/r7platform-portal-web
    restart: always

  portalapi:
    image: mophos/r7platform-portal-api
    environment:
      - NODE_ENV=production
      - R7PLATFORM_PORTAL_API_DB_HOST=192.168.10.28
      - R7PLATFORM_PORTAL_API_DB_PORT=5432
      - R7PLATFORM_PORTAL_API_DB_NAME=r7platform
      - R7PLATFORM_PORTAL_API_DB_SCHEMA=libs
      - R7PLATFORM_PORTAL_API_DB_USER=mk_pgsql
      - R7PLATFORM_PORTAL_API_DB_PASSWORD=rawdata_,sklki8k,28
      - R7PLATFORM_PORTAL_API_DB_RAW_HOST=192.168.10.28
      - R7PLATFORM_PORTAL_API_DB_RAW_PORT=5432
      - R7PLATFORM_PORTAL_API_DB_RAW_NAME=r7platform
      - R7PLATFORM_PORTAL_API_DB_RAW_SCHEMA=rawdata
      - R7PLATFORM_PORTAL_API_DB_RAW_USER=mk_pgsql
      - R7PLATFORM_PORTAL_API_DB_RAW_PASSWORD=rawdata_,sklki8k,28
      - R7PLATFORM_PORTAL_API_SECRET_KEY=8zciriK9gr6oD74sNEp9aEtmSH5P6ncc
      - R7PLATFORM_PORTAL_API_LOGIN_ENDPOINT=https://r7.moph.go.th/platform/test/auth
    restart: always
